Repository vmware-labs/mod_wasm, pull requests merged in 2023-05, with the labels that each got.

#45 fix: Bump Wasmtime to 8.0.1 to address CVE
  CHANGELOG.md
  wasm_runtime/Cargo.lock
  wasm_runtime/Cargo.toml
Labels: cla-not-required, ⬆️ update

#47 fix: Downgrading Wasmtime to `7.0.1` for regression issue on Windows
  CHANGELOG.md
  mod_wasm/modules/wasm/mod_wasm.h
  wasm_runtime/Cargo.lock
  wasm_runtime/Cargo.toml
  wasm_runtime/include/version.h
Labels: ⚠️ bug, cla-not-required

#50 Adding preliminary unit tests and integration tests for `wasm_runtime.so`
  wasm_runtime/Cargo.toml
  wasm_runtime/src/c_api.rs
  wasm_runtime/src/config.rs
  wasm_runtime/src/execution_ctx.rs
  wasm_runtime/src/ffi_utils.rs
  wasm_runtime/src/lib.rs
  wasm_runtime/src/module.rs
  wasm_runtime/src/wasi_ctx.rs
  wasm_runtime/src/wasm_engine.rs
  wasm_runtime/tests/common/mod.rs
  wasm_runtime/tests/integration_tests.rs
Labels: cla-not-required

#51 chore: fix indentation in `mod_wasm.c`
  mod_wasm/modules/wasm/mod_wasm.c
Labels: cla-not-required

#52 feat: Adding Dockerfile to ease try Archive_Tar vulnerability
  examples/exploit-examples/Archive_Tar/Dockerfile.archive_tar
  examples/exploit-examples/Archive_Tar/run.sh
  examples/exploit-examples/README.md
Labels: cla-not-required

#53 Support mapping SCRIPT_FILENAME based on WasmMapDirs
  README.md
  mod_wasm/docs/manual/mod/mod_wasm.html.en.utf8
  mod_wasm/docs/manual/mod/mod_wasm.xml
  mod_wasm/modules/wasm/mod_wasm.c
  wasm_runtime/Cargo.lock
  wasm_runtime/Cargo.toml
  wasm_runtime/include/wasm_runtime.h
  wasm_runtime/src/c_api.rs
  wasm_runtime/src/config.rs
Labels: cla-not-required
